name: Auto Workspace
on: workflow_dispatch
jobs:
  Install And Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: npm install -g typescript
      - run: npm install -g ts-node

      - run: ts-node main.ts
